version: '3'

services:

  mongodb:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017
    networks: 
      - interna

  nodeapitypescript:
    image: andrepapaz/nodeapitypescript
    environment:
      - WAIT_HOSTS=mongodb:27017
      - DO_JWT_VALIDATION=true
    ports:
      - 3000:3000
    networks: 
      - interna
    depends_on: 
      - "mongodb"

networks: 
  interna:
    driver: bridge